# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#

 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"
 git:
    depth: 3
 notifications:
    slack:
        rooms:
            - secure: M/XFpndHi6Bo0NLwifM8IkUxyfJ3L9nlM83hO3rwqEC7IAK2nw/YAX2d4bNWgnMh924ONgGOPtE7aGR0prpJA77x7iOgr+giRobBQvQKaxSrisrNd+LPUTieGUZl0pyt9GPcA53TppbOC+bsPGEpsORQgalg3/+0O2wVnMswMzqh7SzFPqWxw2UI0nVkZvgSrwvJw7r6paCbDay3NDKgad9qVWq6EJl7a6VYtuOjeGKHq6sJI82PQQIiknYRfN2Z7FctmX8EXZqEnLv5vVk2Eul8ZSoFYIG3lT1Nmtw2w4VkbpNXMqh54tL0JbjHQXLU70RC3vVoltBnMEj1WrhFdSV0RFUmGHEglHmyXmewyuBt2fFfrKTcZvpNnxt/tJsQFRH0GYAby8v81hSb9LijBjHuEYb5NNk+OrQ2vgbnY6hmrL0Y9xdRfxfQgxmYMpjnCxbvxUGxcYCxmB/hmiZzH71PGB+HLyRj6RvRNT8ddaQgf0eR/57n4HXDMbxav8Yfk9OxPoZZq2MQd7HEd20qHIZHRG0qfskWOt5+4OHIiueUmFBIUrmMJ3e6GaBZRbShwCWCWwjUEBiepfPacO3mII0h+H7f9voKNsJv81q9/qqQfDfg1QyyQj0w6CKfrchxRw4SPHvS8d/lzxxjegdCQaB1lzJvZg6ez3nz4gtxkf8=
        on_success: always
        on_failure: always
 jobs:
     include:
        - name: build
          stage: build
          if: branch = develop
          install:
              - pip install -U platformio
              - platformio update 
          script:
              - platformio run && platformio run --target buildfs 


        - name: beta_build
          stage: build
          if: branch =~ ^v[0-9]+\.[0-9]+\.[0-9]+_.+
          install:
              - pip install -U platformio
              - platformio update
          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            file:
                - ./.pioenvs/esp8285/firmware.bin
                - ./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: true
            draft: true
            api_key:
                secure: tZAdW+bg9hEt9K476ADAb5IQTYQUoUNmsrdcEOsHmnrX2iDGcaFoeZUJsEVqav2iMFtSl8EOO6wnsQTZ2AWw998cZU7FsLTnOWs357IUcJGg7W82WCfMdRmdSWwp2I/PncbK7Yjjmcz62LKQ1QPBrxM8IkPvIbi9fcPkaxNHFWcC2Fy91szUqwAXxr32TGd3zHRcnWedEMvHmv9O+8Z+miMwYCCYb22WP5i3JKekOKeXLfcuh4bJIa6wdQ5HBqasou8ufHW2ovRvH0Hxzvom5EwEu+VENH/X98sZhJir1n4D0LJgiQg8gG0YdZd12kwXchiOeYK77Yc2mFXBFRqCRMvD0+GUNtTi6O1zArY1tfw1GMQj3fOPK4es4CBJTZ1YuMEZPudhum0976exyjU/aEd1nBkvjn5Lt83PkclKif8FsawIQweAqeYO4RJzkF/9cZux75bwAmqf70VVBobLgMC4x+yO3OhHNNZ6iCrEb/sMOadvTBGB9hTocFqbVnWPakgcP49gCW3ynq1j0l3MMhLriZWzOJs6d0Wk3Qo/FkZ8v+iG9ZS8R/5j+2K+XSxJNc0Mu8SUZYDTr3VxFFW9yDeTgPzsvkxhqgn4lrHiGqc+4bAvaDnIcwUTpLkjwuc+tkoXMf26rZ0w/cJDTu4uXGrsnf9WwTTtm6Nu+8VUmWc=
            on: 
                all_branches: true
                repo: WLANThermo-nano/WLANThermo_nano_Software



        - name: release_build
          stage: build
          if: branch =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
          install:
              - pip install -U platformio
              - platformio update
          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            file:
                - ./.pioenvs/esp8285/firmware.bin
                - ./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: false
            draft: true
            api_key:
                secure: tZAdW+bg9hEt9K476ADAb5IQTYQUoUNmsrdcEOsHmnrX2iDGcaFoeZUJsEVqav2iMFtSl8EOO6wnsQTZ2AWw998cZU7FsLTnOWs357IUcJGg7W82WCfMdRmdSWwp2I/PncbK7Yjjmcz62LKQ1QPBrxM8IkPvIbi9fcPkaxNHFWcC2Fy91szUqwAXxr32TGd3zHRcnWedEMvHmv9O+8Z+miMwYCCYb22WP5i3JKekOKeXLfcuh4bJIa6wdQ5HBqasou8ufHW2ovRvH0Hxzvom5EwEu+VENH/X98sZhJir1n4D0LJgiQg8gG0YdZd12kwXchiOeYK77Yc2mFXBFRqCRMvD0+GUNtTi6O1zArY1tfw1GMQj3fOPK4es4CBJTZ1YuMEZPudhum0976exyjU/aEd1nBkvjn5Lt83PkclKif8FsawIQweAqeYO4RJzkF/9cZux75bwAmqf70VVBobLgMC4x+yO3OhHNNZ6iCrEb/sMOadvTBGB9hTocFqbVnWPakgcP49gCW3ynq1j0l3MMhLriZWzOJs6d0Wk3Qo/FkZ8v+iG9ZS8R/5j+2K+XSxJNc0Mu8SUZYDTr3VxFFW9yDeTgPzsvkxhqgn4lrHiGqc+4bAvaDnIcwUTpLkjwuc+tkoXMf26rZ0w/cJDTu4uXGrsnf9WwTTtm6Nu+8VUmWc=
            on: 
                all_branches: true
                repo: WLANThermo-nano/WLANThermo_nano_Software
